server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"

clients:
  - url: "http://loki:3100/loki/api/v1/push"

positions:
  filename: "/var/log/positions.yaml"
  sync_period: 10s

scrape_configs:
#   - job_name: system
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: varlogs
#           agent: promtail
#           __path__: "/var/log/*log"

  - job_name: system
    kubernetes_sd_config:
      - targets:
          - localhost
        labels:
          job: varlogs
          agent: promtail
          __path__: "/var/log/*log"





          