# my global config
global:
    scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s).

    external_labels:
        monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']

  - job_name: 'safe-boda-go-app'
    static_configs:
      - targets: ['docker.for.mac.localhost:3009']