{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bucketlist-app.serviceAccountName" . }}
  labels:
{{ include "bucketlist-app.labels" . | nindent 4 }}
{{- end -}}
